---
- name: Tarefas comuns para desktops
  hosts: desktops

  roles:
    - role: ajholanda.googlechrome
      tags: googlechrome
    - libreoffice
    - netbios
    - user

- name: Desktops de desenvolvedores
  hosts: devs
  roles:
    - role: ajholanda.vscode
      tags: vscode

- name: Laboratório de informática
  hosts: labs
  roles:
    - power