---
- hosts: localhost
  tasks:
    - name: Erro de sintaxe
      debug: msg="Em aberto'
      ignore_errors: true

        #    - name: Tentando dar um ping
        #      pong:
        #      ignore_errors: true
        #      tags: err0

    - name: Comete erro
      shell: /bin/false 
      tags: err1

    - name: Tenta dizer a verdade
      shell: /bin/true
      ignore_errors: true

