---
- hosts: localhost
  vars:
    myvar: "My Variable"

  tasks:
  # - name: Tarefa
  #   debug: msg="Texto em aberto'

  # - name: Tarefa
  #   debug: msg="{{ myvar }"

  # - name: Tarefa
  # debug: msg="Texto ok"

  # - name: Tentando dar um ping
  #   pong:

  # - name: Copia o arquivo de inventário
  #   copy:
  #     path: hosts.ini
  #     dest: /etc/ansible/hosts

  - name: Comete erro
    command: /bin/false
    tags: err0

  - name: Tenta listar arquivo que não existe
    command: ls /tmp/fooo.txt
    tags: err1

  - name: Ignora o erro
    command: /bin/false
    ignore_errors: true
    tags: err2

  - name: Não interpreta false como erro
    command: /bin/false
    register: status
    failed_when: status.rc != 1
    tags: err3

  - name: Arquivo não deve existir
    command: ls /tmp/passwd
    register: status
    failed_when:
      - status.rc != 0
      - '"No such" not in status.stderr'
    tags: err4

  - name: Checa conectividade
    command: ping -c 1 web.example.net
    register: status
    failed_when: >
      status.rc != 0
      or "100% packet loss" in status.stdout
    tags: err5

- hosts: lab
  any_errors_fatal: true
  tasks:
    - name: Usa any_errors_fatal
      block:
        - name: Primeira tarefa
          debug: msg="Executa em todos os hosts"

        - name: Segunda tarefa falha somente em lab01
          command: /bin/false
          when: inventory_hostname == "lab01.example.net"

        - name: Terceira tarefa
          debug: msg="Nunca é executada"
      tags: err6

- hosts: webservers
  max_fail_percentage: 40
  tasks:
    - name: Atualiza o SO (apt full-upgrade)
      apt: upgrade=full
      tags: err7

    - name: Aviso
      debug: msg="Pelo menos 60% dos hosts foram atualizados"
      tags: err7

- hosts: webservers
#  force_handlers: true
  tasks:
  - name: Força execução dos manipuladores
    block:
      - name: Habilita o módulo userdir
        command: a2enmod userdir

      - name: Copia a configuração do módulo userdir
        copy:
          src: files/userdir.conf
          dest: /etc/apache2/mods-available/userdir.conf
        notify:
          - restart apache2

      - name: Provoca falha
        command: /bin/false
    tags: err8
    when: ansible_os_family|lower == "debian"

  handlers:
  - name: restart apache2
    service: name=apache2 state=restarted
