- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - command: df -h # Retorna a informação de uso dos discos.
      register: disk_usage

    - name: imprime as informações de uso dos discos.
      debug:
       var: disk_usage.stdout

    - name: Cria diretórios.
      ansible.builtin.file:
      path: "~/ansible/{{ item }}"   # Errado.
      state: directory     # Errado.
      with_items:
      - 'files'
      - 'roles'
      - 'tasks'
