# webserver.yml
---
- name: Administra servidores web
  hosts: webservers

  tasks:
  - name: Instala o apache
    package:
      name: apache2
    tags: webserver, webserver_install

  - name: Habitita inicialização e inicializa o apache
    service:
      name: apache2
      enabled: yes
      state: started
    tags:
      - webserver
      - webserver_started
