---
- name: Garante a execução em sistemas Linux apenas
  ansible.builtin.assert: { that: "ansible_system == 'Linux'" }

- name: Inclui tarefas do arquivo server.yml
  include_tasks: server.yml
  when: inventory_hostname in groups['servers']
  tags: sshserver

- name: Inclui tarefas do arquivo workstation.yml
  include_tasks: workstation.yml
  when: inventory_hostname in groups['workstations']
  tags: sshserver
