---
- name: Altera as configurações do servidor ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^{{ item.re }}"
    line: "{{ item.ln }}"
    validate: "sshd -t -f %s"
    backup: yes
  with_items:
    - re: "PasswordAuthentication"
      ln: "PasswordAuthentication no"
    - re: "PermitRootLogin"
      ln: "PermitRootLogin no"
  notify: restart sshd
  tags: sshserver
