---
driver:
  name: docker
platforms:
  - name: instance-debian
    image: debian/latest
    privileged: true
    pre_built_image: true
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  lint:
    name: ansible-lint
verifier:
  name: ansible
