---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: instance-debian
    image: debian:latest
    pre_built_image: true

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_CONFIG: "../../ansible.cfg"
    ANSIBLE_ROLES_PATH: "../../roles"

verifier:
  name: testinfra
  directory: tests/
  options:
    verbose: true
