---
- name: Instala/atualiza
  package: name=sssd

- name: Copia o arquivo de configuração
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: "0600"

- name: Habilita e reinicializa o serviço
  service: name=sssd enabled=yes state=restarted
