---
- name: Instala
  package: name=fail2ban
  tags: fail2ban

- name: Inicializa e habilita o serviço
  service:
    name: fail2ban
    enabled: yes
    state: started
  tags: fail2ban

- name: Personaliza a configuração do jail sshd
  blockinfile:
    path: /etc/fail2ban/jail.local
    backup: yes
    create: yes
    mode: 0644
    block: |
      [sshd]
      enabled = true
      maxretry=6
      findtime = 350
      bantime = 600
    marker: "# {mark} ANSIBLE MANAGED BLOCK fail2ban.sshd"
  notify: restart fail2ban
  tags: fail2ban