---
- name: Instala dnsmasq
  package: name=dnsmasq
  tags: dnsmasq

- name: Garante a existência do diretório raiz do dnsmasq
  file:
    path: /etc/dnsmasq.d
    state: directory
    owner: dnsmasq
    group: nogroup
    mode: '0755'
  tags: dnsmasq

- name: Copia o arquivo de configuração
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: dnsmasq
    group: nogroup
  notify: restart dnsmasq
  tags: dnsmasq

- name: Inclui tarefas do subsistema DHCP
  include_tasks: dhcp.yml
  tags: dnsmasq
