---
- assert:
    that:
      - docker_php_state in ['absent', 'present']
  when: docker_php_state is defined
  tags: docker, docker_php

- name:  Garante que o estado da imagem PHP seja {{ docker_php_state }}
  docker_image:
    name: "php:apache"
    source: pull
    state: "{{ docker_php_state }}"
  tags: docker, docker_php

- name: Garante que o diretório de armazenamento de dados exista
  file:
    path: "{{ docker_php_volume }}"
    state: directory
  when: docker_php_state == "present"
  tags: docker, docker_php

- name: Garante que o contêiner PHP esteja sendo executado
  docker_container:
    name: "php_apache"
    image: "php:apache"
    state: started
    ports:
      - "{{ docker_php_port }}:80"
    volumes:
      - "{{ docker_php_volume }}:/var/www/html"
  when: docker_php_state == "present"
  tags: docker, docker_php